version: '3.3'

services:

  homehub-metrics-exporter:
    container_name: homehub-metrics-exporter
    image: jamesnetherton/homehub-metrics-exporter
    ports:
      - 19092:19092
    command:
      - '--hub-password='

  grafana:
    container_name: grafana
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    ports:
      - 3000:3000
    volumes:
      - ./etc/grafana/provisioning/:/etc/grafana/provisioning/

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.5.0
    volumes:
      - ./etc/prometheus/server/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
